pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectUpdateView, ProjectListView, ProjectDeleteView

app_name = 'projectapp'
urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ProjectUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

projectapp/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=200, null=True)
    description = models.TextField(null=False)
    image = models.ImageField(upload_to='project/', null=False)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


# Create your views here.
class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 25


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None
        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list,
                                                               subscription=subscription,
                                                               **kwargs)


class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectCreationForm
    context_object_name = 'target_project'
    template_name = 'projectapp/update.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(DeleteView):
    model = Project
    context_object_name = 'target_project'
    success_url = reverse_lazy('projectapp:list')
    template_name = 'projectapp/delete.html'

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Create Project</h4>
        </div>
        <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Project : {{ target_project.title }}</h4>
    </div>
    <form action="{% url 'projectapp:delete' pk=target_project.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div style="text-align:center; max-width: 500px; margin: 4rem auto 1.5rem auto;">

            <img src="{{ target_project.image.url }}"
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
            <h2 style="font-family: 'NanumSquareB'">
                {{ target_project.title }}
            </h2>
            <h5>
                {{ target_project.description }}
            </h5>
        </div>

        <div class="text-center mb-5">
            {% if user.is_authenticated %}
                {% if not subscription %}
                <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
                    class="btn btn-primary rounded-pill px-4">
                Subscribe
                </a>
                {% else %}
                <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
                    class="btn btn-dark rounded-pill px-4">
                Unsubscribe
                </a>
                {% endif %}
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>

    </div>
{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
  .container {
    padding: 0;
    margin: 0, auto;
  }

  .container div {
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 1rem;
  }
  .container img {
    width: 7rem;
    height: 7rem;
    object-fit: cover;
    border-radius: 1rem;
  }
</style>

{% if project_list %}
<div class="container">
  {% for project in project_list %}
  <a href="{% url 'projectapp:detail' pk=project.pk %}">
    {% include 'snippets/project_card.html' with project=project %}
  </a>
  {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div>
  <h1 style="text-align:center">No Projects yet!</h1>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}


<div style="text-align:center">
 <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3 mb-3">
   Create Project
 </a>
</div>

<script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

projectapp/templates/projectapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Project Update</h4>
        </div>
        <form action="{% url 'projectapp:update' pk=target_project.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}